### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by BradleyJinks** [BradleyJinks/GameZone#24]
**Features**
Contact
- [ ] Create contact request
- [ ] Delete contact requests

Game
- [ ] Create Game
- [ ] Update Game
- [ ] Delete Game
- [ ] Display Game
- [ ] Find Game
- [ ] Validate Inputs
- [ ] Setup Migration to help with validation

Game Media
- [ ] Add images to a game
- [ ] Remove images to a game

Game Rating
- [ ] Update the rating of a game once a comment is added
- [ ] Update the rating of a game once a comment is removed
- [ ] Update the rating of a game every 5 mins instead of after each comment

Comments
- [ ] Create Comment
- [ ] Update Comment
- [ ] Delete Comment
- [ ] Display All Comments for that user
- [ ] Find Game
- [ ] Validate Inputs
- [ ] Setup Migration to help with validation

Settings
- [ ] Update profile image
- [ ] Update profile background
- [ ] Update user details

**Wont Implement**

Star comments
- [ ] Star Comment
- [ ] Un-Star Comment
- [ ] Show all started comments
